apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-blue
  labels:
    app: webserver-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-blue
  template:
    metadata:
      labels:
        app: webserver-blue
    spec:
      containers:
      - name: webserver-blue
        image: pato23arg/api-endpoint:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
