apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: 628641662978.dkr.ecr.eu-west-1.amazonaws.com/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
